# Generated by Django 5.2 on 2025-04-28 09:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markdown_path', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['title'], name='prompts_pro_title_fa9f36_idx')],
            },
        ),
    ]
